language: python

dist: xenial

notifications:
  on_success: change
  on_failure: always

matrix:
  include:
  - python: 3.5
    env: TOXENV=py35 ES_VERSION=6.6.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-${ES_VERSION}.tar.gz
  - python: 3.6
    env: TOXENV=py36 ES_VERSION=6.6.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-${ES_VERSION}.tar.gz
    addons:
      postgresql: "9.6"
  - python: 3.6
    env: TOXENV=py36 PGPORT=5432 ES_VERSION=6.6.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-${ES_VERSION}.tar.gz
    addons:
      postgresql: "10"
      apt:
        packages:
        - postgresql-10
        - postgresql-client-10

install:
- wget ${ES_DOWNLOAD_URL}
- tar -xzf elasticsearch-oss-${ES_VERSION}.tar.gz
- ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
- travis_retry pip install -U setuptools pip tox

script:
- travis_retry tox -- -vv

services:
- postgresql
- redis

before_script:
  - psql -c "create user test with encrypted password 'test';" -U postgres
  - psql -c 'create database appenlight_test owner test;' -U postgres

after_success:
- pip install coveralls
- coveralls
