language: python

dist: xenial

notifications:
  on_success: change
  on_failure: always

matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
    addons:
      postgresql: "9.6"
  - python: 3.6
    env: TOXENV=py36 PGPORT=5432
    addons:
      postgresql: "10"
      apt:
        packages:
        - postgresql-10
        - postgresql-client-10

install:
- travis_retry pip install -U setuptools pip tox

script:
- travis_retry tox

services:
- postgresql
- elasticsearch
- redis

before_script:
  - psql -c "create user test with encrypted password 'test';" -U postgres
  - psql -c 'create database appenlight_test owner test;' -U postgres

after_success:
- pip install coveralls
- coveralls
